<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- Informations de l'application -->
    <AssemblyName>GestiParc</AssemblyName>
    <Product>GestiParc - Gestion de Parc Informatique</Product>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Company>Dr-Revdev</Company>
    <Copyright>Copyright © 2025</Copyright>
    <Description>Application de gestion de parc informatique et d'équipements</Description>
    <ApplicationIcon>GestionParc.ico</ApplicationIcon>
    
    <!-- Configuration de publication -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="database\parcdatabase.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>